# Project: advLoginSystem
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = loginSystem.o
LINKOBJ  = loginSystem.o
LIBS     = -L"D:/Dev C++/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Dev C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev C++/Dev-Cpp/TDM-GCC-64/include" -I"D:/Dev C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Dev C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Dev C++/Dev-Cpp/TDM-GCC-64/include" -I"D:/Dev C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Dev C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Dev C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = advLoginSystem.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Dev C++\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

loginSystem.o: loginSystem.cpp
	$(CPP) -c loginSystem.cpp -o loginSystem.o $(CXXFLAGS)
